version: 2.1
orbs:
  node: circleci/node@5
jobs:
  checkoutEtTests:
    machine: true
    steps:
      - run: git clone https://github.com/mathernn/backend.git
      - run:       
            command: |
                    cd backend
                    npm install 
      - run: 
            command: |
                    cd backend
                    npm test domain.test.js


workflows:
  build: 
    jobs: 
    - checkoutEtTests
