version: 2.1
orbs:
  node: circleci/node@5

jobs:
  checkoutEtTests:
    machine: true
    steps:
      - run: git clone https://github.com/mathernn/backend.git
      - run:
          command: |
            cd backend
            npm install 
      - run:
          command: |
            cd backend
            npm test domain.test.js

  integrationFrontend:
    machine: true
    steps:
      - run: git clone https://github.com/mathernn/backend.git
      - run: git clone https://github.com/mathernn/frontend.git
      - run:
          command: |
            cd frontend
            npm install
      - run:
          command: |
            cd frontend
            npm run build
      - run:
          command: |
            cd backend
            mkdir public

      - run:
          command: |
            cd backend
            cp -rT ../frontend/build ./public

      - persist_to_workspace:
          root: .
          paths:
            - backend/public

  deploiement:
    machine: true
    steps:
      - attach_workspace:
          at: .

      - run:
          command: |
            cd backend
            ls -Rl

workflows:
  build:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
