version: 2.1
orbs:
  node: circleci/node@5
jobs:
  checkoutEtTests:
    machine: true
    steps:
      - run: 
          command: |
            git clone git@github.com:mathernn/backend.git
            cd backend
            npm install 


workflows:
  build: 
    jobs: 
    - checkoutEtTests
